### ISSUE TITLE
Add a a way to specify descriptions and default values using dynaconf_validaors.toml

### ISSUE THREAD

**Issue by dmfigol** [rochacbruno/dynaconf#115]
Hi,
thank you for the library. It really improved the way I approach configuration files.
Finally I have types and proper sections.
What I am missing is schema: I would love to be able to enforce that some parameters are obligatory, their type and provide a description, also raise an exception if there is some unknown parameter is configured.
I *think* I could use something like `marshmallow` for that, but if it is part of this library, it would be great for my use-cases.
What do you think?

UPD: after looking at the docs more, I think validators would solve majority of our use-cases, but I don't see a way to specify descriptions and default values in a nice way, so that they are automatically populated in our docs.

**Comment by rochacbruno** [comment]
Yeah the validators are the way to go https://dynaconf.readthedocs.io/en/latest/guides/validation.html

It would be easy to include support for `descriptions` which would be only useful for printing and showing help message.

About the default values we can think about making dynaconf to look to the validation file before loading its data.

**Comment by rochacbruno** [comment]
thinking a bit more, in the same way we have `.secrets.` maybe we can add support for a special `.defaults.` file, so when it is present dynaconf loads it first.

**Comment by brucegibbins** [comment]
I think this would be a great addition as well. Something that could help validate the config file. Especially looking for required elements or a key that exists but is missing a value or perhaps checking against valid value list
Cheers
-------- Original message --------From: Dmitry Figol <notifications@github.com> Date: 23/1/19  4:24 am  (GMT+10:00) To: rochacbruno/dynaconf <dynaconf@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [rochacbruno/dynaconf] Schema for dynaconf config (#115) 
Hi,

thank you for the library. It really improved the way I approach configuration files.

Finally I have types and proper sections.

What I am missing is schema: I would love to be able to enforce that some parameters are obligatory, their type and provide a description, also raise an exception if there is some unknown parameter is configured.

I think I could use something like marshmallow for that, but if it is part of this library, it would be great for my use-cases.

What do you think?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/rochacbruno/dynaconf","title":"rochacbruno/dynaconf","subtitle":"GitHub repository","main_image_url":"https://github.githubassets.com/images/email/message_cards/header.png","avatar_image_url":"https://github.githubassets.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/rochacbruno/dynaconf"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Schema for dynaconf config (#115)"}],"action":{"name":"View Issue","url":"https://github.com/rochacbruno/dynaconf/issues/115"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/rochacbruno/dynaconf/issues/115",
"url": "https://github.com/rochacbruno/dynaconf/issues/115",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by rochacbruno** [comment]
After #146 validators will be a plugin, then we can work on this

**Comment by rochacbruno** [comment]
Now we can define default values using validators,   the  `validators.toml` is still missing this support

Details here: https://www.dynaconf.com/validation/#providing-default-or-computed-values 

We still need

- Define description/help for a setting value in the validator (or  as a schema class)
- Support description, default in toml validator
- Add a way  to  generate initial settings file   based on  validator.

**Comment by bottomqueer** [comment]
Hey.. Im a girly guy.. Bottom bitch u can fuck looking today.. I wear girl clothes paint my nails hit me up 865 888 1285
Knoxvilletn37918@gmail.com

**Comment by bottomqueer** [comment]
Hey.. Im a girly guy.. Bottom bitch u can fuck looking today.. I wear girl clothes paint my nails hit me up 865 888 1285
Knoxvilletn37918@gmail.com

**Comment by linwilai918** [comment]
https://github.com/rochacbruno/dynaconf/issues/115#issuecomment-456583088
