### ISSUE TITLE
YAML.load without a loader is deprecated for security purposes

### ISSUE THREAD

**Issue by dmsimard** [rochacbruno/dynaconf#127]
We've started seeing the following warning:
```
lib/python3.6/site-packages/dynaconf/loaders/base.py:95: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
```

See here: https://github.com/yaml/pyyaml/wiki/PyYAML-yaml.load(input)-Deprecation

**Comment by rochacbruno** [comment]
@dmsimard thanks for reporting.

we have some options now

The current Loader choices are:
```
    BaseLoader

    Only loads the most basic YAML

    SafeLoader

    Loads a subset of the YAML language, safely. This is recommended for loading untrusted input.

    FullLoader

    Loads the full YAML language. Avoids arbitrary code execution. This is currently (PyYAML 5.1) the default loader called by yaml.load(input) (after issuing the warning).

    UnsafeLoader (also called Loader for backwards compatability)

    The original Loader code that could be easily exploitable by untrusted data input.
```
You may also use one of the shortcut "sugar" methods:
```
    yaml.safe_load
    yaml.full_load
    yaml.unsafe_load
```

I am inclined to keep using the `unsafe_load` because I know some users which are using `!!python` and `!!bash` tokens.

Another options is to default to `safe_load` and have a config var `YAML_LOADER_FOR_DYNACONF=safe_load|full_load|unsafe_load`

**Comment by dmsimard** [comment]
@rochacbruno defaulting to unsafe_load is more or less the current approach that pyyaml took for similar reasons.
As a user of dynaconf, I'd expect to be able to use safe_load if I don't need unsafe_load -- a configuration option is fine.

The only thing I would make sure is that if unsafe_load is used, the deprecation/security warning is still printed. Users need to be aware that safe_load is preferred.
