### ISSUE TITLE
[RFC] Rename GLOBAL_ENV_ to ENV_PREFIX_ ?

### ISSUE THREAD

**Issue by rochacbruno** [rochacbruno/dynaconf#166]
In the beginning dynaconf supported changing working environment for env vars and then it made sense to name it `GLOBAL_ENV_FOR_DYNACONF`.

But now, this variable is used **only** to control the environment variable prefix and the name is not good, the **global** in it can confuse people.

I suggest:

Rename `GLOBAL_ENV_FOR_DYNACONF` to `ENV_PREFIX_FOR_DYNACONF` then the name will be clear.

Renaming will not break compatibility, the old wll still work but users will see a `WARNING` message.

Comments?

**Comment by rochacbruno** [comment]
@janw what do you think about this?

**Comment by janw** [comment]
I have to admit that this *did* confuse me at first, when we started looking into Dynaconf 😅  So that would be a very welcome change IMHO. And even with `ENV_PREFIX_FOR_DYNACONF` there's still some confusion as "ENV" can mean both "environment variables" and "working environment" (as in: production, development, testing, etc.). Looking at the [configuration guide](https://dynaconf.readthedocs.io/en/latest/guides/configuration.html) all variables starting with `ENV_` are related to the working environment, so I'd suggest going with ENVVAR_PREFIX_FOR_DYNACONF instead here, to avoid mixing them up.
