### ISSUE TITLE
Correct usage of ENVVAR_PREFIX_ vs. ENV_

### ISSUE THREAD

**Issue by janw** [rochacbruno/dynaconf#177]
I think some clarification is required on the different use-cases of the new ENVVAR_PREFIX vs.  using ENV. There are multiple occurrences throughout dynaconf that are very confusing and use ENVVAR_PREFIX where I would have expected ENV to be used, for example:

* https://github.com/rochacbruno/dynaconf/blob/1bb2c39ae6a39cbbd32ca8ef39ef7ea5732a9418/dynaconf/base.py#L842
* https://github.com/rochacbruno/dynaconf/blob/1bb2c39ae6a39cbbd32ca8ef39ef7ea5732a9418/dynaconf/contrib/flask_dynaconf.py#L50
* https://github.com/rochacbruno/dynaconf/blob/e48521790a72fa4756a9d0eb8d715da562642f25/dynaconf/cli.py#L468-L469
* https://github.com/rochacbruno/dynaconf/blob/3ba4ed1f0a929289a111157e1d6c06b2d072925a/dynaconf/loaders/base.py#L125

These all seem to expect a value that is actually the "working environment" (we discussed the difference in #166), yet they *use* the environment variable prefix.

**Comment by rochacbruno** [comment]
Awesome! good catch again :100: 

On 1)

https://github.com/rochacbruno/dynaconf/blob/1bb2c39ae6a39cbbd32ca8ef39ef7ea5732a9418/dynaconf/base.py#L842 

When reading a feature flag (mostly from redis) if env is not defined it should have a default prefix, it used to be `DYNACONF` so I think we need that same fix you did on your latest PR To catch the `False` case.

`env = env or self.ENVVAR_PREFIX_FOR_DYNACONF or 'DYNACONF'`

on 2)

It is a typo, should be `ENV_VAR_PREFIX_` and in that case will default to `FLASK_`

https://github.com/rochacbruno/dynaconf/blob/1bb2c39ae6a39cbbd32ca8ef39ef7ea5732a9418/dynaconf/contrib/flask_dynaconf.py#L50

on 3)

It is ok! solving 1) that will make sense, maybe it needs better English on that help text.

```
 help=(
        "specify the env to write the passed data " 
        "it defaults to DEVELOPMENT for settings files. "
        "For external sources like Redis and Vault "
        "it will be `DYNACONF` or the value set in "
        "$ENVVAR_PREFIX_FOR_DYNACONF"
    )
```

Note that on redis it may be also possible to have no prefix at all, instead of writing `DYNACONF_FOO=bar` user may want to write only `FOO=bar`. I am not sure if it is ok or if we should enforce a prefix fr redis and vault servers.

https://github.com/rochacbruno/dynaconf/blob/e48521790a72fa4756a9d0eb8d715da562642f25/dynaconf/cli.py#L468-L469

on 4)

It also needs your fix for the `False` problem, it is just a DEBUG message telling that the `[env]` is not defined on the current reading file.

```
 if env not in (self.obj.get("ENVVAR_PREFIX_FOR_DYNACONF") or 'DYNACONF',  "GLOBAL"):
```

https://github.com/rochacbruno/dynaconf/blob/3ba4ed1f0a929289a111157e1d6c06b2d072925a/dynaconf/loaders/base.py#L125 


---

Maybe to clarify this confusions we need to set the standard of using `env` to refer to current working environment like `development, production...`  and always use `envvar` when refering to environment variables.

That confusion exists because in the past `env` was named `namespace` but we renamed.

**Comment by janw** [comment]
> Maybe to clarify this confusions we need to set the standard (…)

That makes perfect sense. Maybe even have a small text snippet for clarification in the documentation, so people know what to expect when they encounter `env` vs. `envvar`?
