### ISSUE TITLE
[RFC] Callback to new settings (feature flag)

### ISSUE THREAD

**Issue by fabiosoft** [rochacbruno/dynaconf#180]
**Is your feature request related to a problem? Please describe.**
My application need to react to a configuration as quick as configuration changes, without killing itself or redeploy... for example when the host url changes, it must discard previous connection and establish new one.

**Describe the solution you'd like**
I'd like to have a method callback where a can specify the setting key to monitor and get notified. Something like:
```python
settings.subscribe('host', callbackFunction)
```

**Describe alternatives you've considered**
By now i'm using a while loop keeping reading fresh value from settings (redis) waiting to change, and the manually call my function.
But i think this approach is very inefficient considering resources and thread blocks.

```python
while settings.get_fresh("host") != currentHost:
    pass
# then...
reload()
```

I hope you can put me on the right way

**Comment by rochacbruno** [comment]
I'll think about, there must be some heartbeat service running because Dynaconf is passive.

**Comment by rochacbruno** [comment]
I did some research and the way to implement this feature is:

1) Using Redis

- Option 1: Subscribe to notifications https://redis.io/topics/notifications
- Option 2: Use SYNC
- Option3: Use redis-monitor

2) Using settings files
- Setup a Python watchdog to emit a signal ans ude thsi signal to reload dynaconf.

**Comment by rochacbruno** [comment]
This is a candidate for a plugin

**Comment by thomaslundstrom** [comment]
I have an alternative thought about this, @rochacbruno, though I'm guessing the refactoring needed is quite large.

Currently, the `settings` object functions as a cache in dynaconf;

```
import settings from dynaconf

# here dynaconf start a lookup, and assigns all vars inside the default env to settings, then returns the value corresponding to the key `foo`
print(f'settings.foo: {settings.foo}') 

# here dynaconf just returns the value corresponding to `foo` on the currently loaded settings
print(f'settings.foo: {settings.foo}')
```

However, if you use `using_env` that cache is cleared:

```
import settings from dynaconf

# here dynaconf start a lookup, and assigns all vars inside `my_env` to settings
with settings.using_env('my_env'):
  print(f'settings.foo: {settings.foo}') 

# even though we have the same env, dynaconf again starts a lookup and assigns all vars for `my_env` to settings
with settings.using_env('my_env'):
  print(f'settings.foo: {settings.foo}') 
```

Neither of the above is optimal for our regard. I'd like for dynaconf to assign the LazySettings instance to a cache just after the instance is filled with new values. The cache is more or less a `dict` with the env name as the key and the instance as the value. Then, when you switch environment, using either `using_env` or `setenv`, dynaconf either uses the selected environment's cache or loads it if it's non-existing. `fresh` of course clears the cache and reloads the settings instance for that environment (and assigns it to the cache). This means that dynaconf.settings is more or less just a shim for the actual instances in the cache.

The above gives us a cache to work with.

The next step is to add cache invalidation into each type of loader. The redis loader will subscribe to notifications (your item 1 above) and just assign `cache[the_env] = None` whenever a notification happens for `the_env`. Or, for extra points, update the cache instead of having to wait until next access to load it. File loaders will do the same, but listen to changes to the files, of course, and clear (or reload) the cache.

What do you think? Would that be doable in this codebase?

**Comment by rochacbruno** [comment]
This is out of the scope of dynaconf right  now,
However I am happy to  review/accept a Pull  Request if someone comes with a non-breaking implementation.

Thanks, (closing for now)
