### ISSUE TITLE
[RFC] Add method to load_keys

### ISSUE THREAD

**Issue by kedark3** [rochacbruno/dynaconf#211]
**Problem**
Suppose we have a secret store that has layout like this:
![image](https://user-images.githubusercontent.com/8180469/63630714-f763a580-c5eb-11e9-957b-4fe469a9962b.png)

I would like to have a method to list all the keys. 

**Solution**
I have tried following piece of code in Vault_loader.py as:
```
def load_keys(obj, path):
    client = get_client(obj)
    return client.list('/secret/metadata/{}'.format(path))
```
It uses `/secret/metadata` endpoint for Vault and returns the dict that also contains keys. 

**Sample output:**
```
{'request_id': '<redacted>',
 'lease_id': '',
 'renewable': False,
 'lease_duration': 0,
 'data': {'keys': ['secret1', 'secret2', 'secret3']},
 'wrap_info': None,
 'warnings': None,
 'auth': None}

```
I can then do 
```
vault_loader.load_keys(settings, 'sample/')['data']['keys']                                                    
['secret1', 'secret2', 'secret3']
```

**Describe alternatives you've considered**
IMHO, It only fits to use this solution because we have number of different credentials we want to store and retrieve. Another solution would be to dump all credentials under one secret in JSON format like this 
![image](https://user-images.githubusercontent.com/8180469/63630822-e6fffa80-c5ec-11e9-8108-1668fffb14f0.png)

The problem with that is if we have a lot of credentials(keys) in one secret(or environment) then updating one key would mean that I have to load entire data and then update relevant key and write the entire data again. 

**Additional context**
You may contact me on Google Chat/email(Red Hat) if you want to discuss our use case. 
I am fairly new to Vault/Dynaconf, excuse if my understanding is different that how this all is intended to be used.

**Comment by VaultVulp** [comment]
I'm a (sort of :)) active Vault and Dynaconf user and would like to know a little bit more about your use case.

Why do you need to get Vault internal metadata through Dynaconf via additional function? As far as I understand (@rochacbruno can correct me if I'm wrong) - Dynaconf helps us to get one source of truth instead of reading inconsistent data in different modules from different sources such as os.get_env(), config files, .py-file, etc. All this source will be hidden behind the same Dynaconf API: `settings.PATH.KEY`. But in your PR #214 you provide a new API call specifically for Vault.

And still, if you split your secrets in a way described here you won't be able to read this values directly via Dynaconf, due to how `vault_loader.load` works.

**Comment by rochacbruno** [comment]
If I understood correctly, this line

```py
 env_list = [obj.get("DEFAULT_ENV_FOR_DYNACONF")] + _load_keys(obj, path)
```

Will result in something like:

Considering your example of having `secret1, secret2, secret3`:

```py
env_list == ['default', 'secret1', 'secret2', 'secret3', 'dynaconf', 'current_env_in_use', 'global']
```

So in the `load` it does:

```py
for env in env_list:
        path = "/".join([obj.VAULT_PATH_FOR_DYNACONF, env])
        try:
            data = client.secrets.kv.read_secret_version(path)
        ## set each key found in data to settings object.
```

So that means it will try to load keys inside `default`, then `secret1` then `secret2` and so on until it reaches the end of `env_list` and on every iteration it will override if there are existing variables.

Is that what you want?

Because right now you can do `settings.set_env('secret2')` or `with settings.using_env('secret3')` and then programatically control which one do you want to load to `current_env_in_use`

**Comment by rochacbruno** [comment]
Hi @VaultVulp @kedark3 
I understood that the goal is just o have a helper function to list all the `envs` existing on the vault server before one can iterate over it and use `setenv` ot `using_env` to switch to them.

I'll make my suggestiong on the PR #214

**Comment by kedark3** [comment]
Thanks @rochacbruno
