### ISSUE TITLE
Does Dynaconf support multithreading?

### ISSUE THREAD

**Issue by mketiku** [rochacbruno/dynaconf#265]
Hello, does Dynaconf support multithreading?

**Comment by rochacbruno** [comment]
Hi @mketiku 

We assume Dynaconf can work a multithreaded program, each thread may or have its own dynaconf object or share the object.

we don't have tests for multithread cases yet, that would be nice to add some tests under `example` folder.

The only mutable attribute dynaconf has is `current_env` that can be changed at runtime, the test must assert that 2 threads can have different envs at a time.

For that I recommend instead of `using_env` method/context manager, to use the `from_env` because it will clone the settings object as a new object in memory.

I am interested in experimenting and testing it.

**Comment by mketiku** [comment]
Thanks @rochacbruno, I appreciate the response.

**Comment by rochacbruno** [comment]
Dynaconf is running in multi-threading environments
