### ISSUE TITLE
[bug] settings.set with dotted notation limit key names that can be used

### ISSUE THREAD

**Issue by NoamGraetz2** [rochacbruno/dynaconf#384]
you cannot set a deeper entry with the same key as higher entry.

settings.set('a.b', 1)
settings.set('a.c', 2)
settings.set('a.c.k', 22)

--> {'c': {'k': 22}, 'b': 1}

settings.set('a.c.b', 3)

--> {'c': {'b': 3, 'k': 22}}
the higher entry 'a.b' was removed 

the problem lie within _dotted_set and the use of 'tail' and merge

tries to find a quick solution, but i a don't have the time now, will bypass by using different keys :(

**Comment by rochacbruno** [comment]
This is related to the merging strategies #241 (ths issue is closed but we can reopen the discussion)

Do we want `set` to replace an existing key or to contribute to existing keys? I can't find a good solution for this problem.

maybe introduce a new `merge_set`?

**Comment by rochacbruno** [comment]
I figured out the problem now and it is a real bug.

We are passing `tail` to `object_merge` as a keyname and it is wrong, we should change that to accumulate the whole path.

for `a.b.c` instead of passing `tail=c` we really need to recursively accumulate it and compare whole path `a` on first call, `a.b` on second, `a.b.c` on the **tail** call.

Also we should invert the order that dicts are merged on object_merge and instead of taking the `new` as the definitive object use the **old** which will keep all existing keys.

**Comment by rochacbruno** [comment]
Fixed in #415 thanks @NoamGraetz2
