### ISSUE TITLE
Django use dynaconf settings in settings.py?

### ISSUE THREAD

**Issue by lleontop** [rochacbruno/dynaconf#584]
Hi thank you for this amazing library. 
I am using Dynaconf with Django and I have a configuration scenario that seems very trivial but turns out to be very tricky so I wanted to make sure I am not missing something terribly obvious here.

I want to use a mysql database with Django with parameters (username,db name, password) coming from a config file (which includes several other parameters) so in my Django settings.py I would like to use something like:
```
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': this.mysql.Database,
        'USER': this.mysql.User,
        'PASSWORD': this.mysql.Password,
        'PORT': this.mysql.Port,
        'HOST': this.mysql.Host,
        'CONN_MAX_AGE': this.mysql.connection_max_age
    }
}
```
Of course this is not working and the closest I got to have something similar is to define a `user_settings.py` with this:
```
DATABASES = {
    'default': {
        'ENGINE': "django.db.backends.mysql",
        'NAME': "@format {this.mysql.Database}",
        'USER': "@format {this.mysql.User}",
        'PASSWORD': "@format {this.mysql.Password}",
        'PORT': "@format {this.mysql.Port}",
        'HOST': "@format {this.mysql.Host}",
        'CONN_MAX_AGE': "@format {this.mysql.connection_max_age}"
    }
}
```
and then include it in Dynaconf:
```
import dynaconf  # noqa
settings = dynaconf.DjangoDynaconf(__name__,
    DYNACONF_INCLUDE=['user_settings.py'],
    ENVVAR_FOR_DYNACONF='CONFIG_FILE',
    ENVIRONMENTS_FOR_DYNACONF=False) 
```
This kind of works but seems a bit complicated for such a simple scenario and format treats everything as strings so integer values like conn_max_age cannot be casted to int (as I understand format is evaluated after casting and double @int @format is not evaluated) so it breaks non-string values.

I have read about Django explicit mode and it will probably work for my case but this takes away some of the nice things and wanted to make sure I am not missing something here before going down this road! Any help/advise on how to achieve this kind of configuration would be appreciated!

Thanks!

**Comment by whg517** [comment]
Hello, I don't really understand the point of what you're doing. Or what kind of problem you designed it to solve.

I think the current flexibility of DynaConf allows for a number of configuration scenarios.

In my practice, I think 'settings.py' is the default configuration for a project, just like some software with a 0 configuration.For example, MySQL, can be started directly after installation without any configuration changes. Because the project itself has a default configuration.

For a Django project, the default configuration is usually to use the SQLite database, so that someone else can install it and start  it in testing environment or experience environment, can be very simple, and fast to see the results of the project.

In a custom environment or advanced tutorial, tell the user that you can override the default configuration by adding a user configuration to make the project run with a certain amount of personalization. For example, MySQL provides a '/etc/my.cnf' configuration file for users to adjust their personalized parameters.

When working on a Django project, it's easy to do so using DynaConf. Specify using 'DYNACONF_INCLUDE' the user-level configuration that needs to be loaded. Once read by Dynaconf, the configuration defined in 'settings.py' will be overridden. To achieve customization the purpose of.

So, my general approach is generic and works for almost everyone with the default configuration, defined in 'settings.py'. Then through dynaconf reads external configuration such as '<project_path>/settings.local.yml' in the project directory configuration file, this file is not tracked by Git and is stored in the project directory for easy viewing.

In the system directory for example '/etc/project_name/settings.yml' or '/etc/project_name/settings.yml' a configuration file is a file that users can create in the system directory to override the default configuration when the project is deployed.

eg:



Default config **settings.py** :

```python
# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-g=dm9wfr+7n4=%zmhdq$rtwrk*+e0kx)worrti%23x87p@4dpc'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = ['127.0.0.1', 'localhost']

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


import dynaconf  # pylint: disable=wrong-import-position

settings = dynaconf.DjangoDynaconf(
    __name__,
    envvar_prefix='MY_PROJECT',
    settings_files=[
        BASE_DIR / 'settings.local.yml'
    ],
    environments=False,
    load_dotenv=True,
    ENVVAR_FOR_DYNACONF='MY_PROJECT_SETTINGS',
    includes=[
        Path(sys.prefix, 'etc', 'my_project', 'settings.yml'),
    ]
)

```

developer config **settings.local.yml**

```yaml
DEBUG: True

DATABASES:
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: my_project
    USER: root
    PASSWORD: 'root'
    HOST: 127.0.0.1
    PORT: 3306
```

production config **/etc/my_project/settings.yml**

```yaml
ALLOWED_HOSTS:
  - dynaconf_merge
  - example.com
  - *.foo.org

DATABASES:
  default:
    ENGINE: 'django.db.backends.mysql'
    NAME: my_project
    USER: my_project
    PASSWORD: 'fafbv23-nmf934qfj0'
    HOST: 10.10.10.10
    PORT: 6033
```

I hope my answer can help you

**Comment by rochacbruno** [comment]
I hope @whg517 answer solved the problem, if not please reopen the issue.

Thanks whg
