### ISSUE TITLE
[bug] docs don't match behavior for init

### ISSUE THREAD

**Issue by mattsta** [rochacbruno/dynaconf#589]
**Describe the bug**
Docs say:

```haskell
$ dynaconf -i init -v key=value -v foo=bar -s token=1234 -e production
```

But when running:

```haskell
$ dynaconf -i init -v key=value -v foo=bar -s token=1234 -e production
Usage: dynaconf [OPTIONS] COMMAND [ARGS]...
Try 'dynaconf --help' for help.

Error: no such option: -v
```

Removing `-i` lets it work, but the resulting `settings.toml` and `.secrets.toml` files only have the flat k/v created, no `production` or `default` sections are created as the documentation suggests at https://www.dynaconf.com/cli/#dynaconf-init

**Comment by RobertRosca** [comment]
This seems to just be outdated documentation.

`--env/-e` have been deprecated for the `init` command, which is why you only get a flat settings file without the production/default sections.

`--instance/-i` requires a path to an existing settings instance, so it can't be used with `init`.

I've updated the documentation and docstrings for these, as well as added a clearer warning that `-e` is deprecated and has no effect as well as that `--instance` cannot be used with `init` in this PR: https://github.com/rochacbruno/dynaconf/pull/629
