### ISSUE TITLE
[bug] SQLAlchemy URL object replaced with BoxList object

### ISSUE THREAD

**Issue by trickardy** [rochacbruno/dynaconf#595]
Using dynaconf with Flask and Flask-SQLAlchemy. If I initialize dynaconf, then assign a sqlalchemy `URL` object to a config key, the object becomes a `BoxList`, which causes sqlalchemy to fail later. Dynaconf should not replace arbitrary objects.

```python
app = Flask(__name__)
dynaconf.init_app(app)
app.config["SQLALCHEMY_DATABASE_URI"] = sa_url(
    "postgresql", None, None, None, None, "example"
)

print(type(app.config["SQLALCHEMY_DATABASE_URI"]))
```

```
<class 'dynaconf.vendor.box.box_list.BoxList'>
```

This is a problem when using SQLAlchemy 1.4, which treats the URL as an object with attributes instead of a tuple.
 
cc @davidism

**Comment by rochacbruno** [comment]
I think that happens because `sa_url` returns an instance of `list/tuple` and dynaconf needs to encapsulate that data type in to a Box to enable the **dynamic** features, such as templates etc..

I will think in a solution for this problem, maybe we need a way to prevend some specific keys from being transformed to a Box with the drawback of missing the dynamism.

**Comment by davidism** [comment]
Maybe checking exact list type instead of subclass. Or making the box type proxy more methods such as getattr, although that's probably going to get out of hand.
