### ISSUE TITLE
[bug] Cannot merge using env var with dict that has empty string as its key

### ISSUE THREAD

**Issue by bmbouter** [rochacbruno/dynaconf#747]
**Describe the bug**
I tried to use an env_var to merge a dictionary, but it has the key '' which is not able to work, although I expected it to work.

**To Reproduce**
I tried to set this variable:

` PULP_LOGGING={'dynaconf_merge': True, 'loggers': {'': {'handlers': ['console'], 'level': 'DEBUG'}}}`

**Expected behavior**
I expected it to merge, but it does not. When showing the effective config with `dynaconf list` I see it is not merged as expected.

**Comment by rochacbruno** [comment]
@bmbouter this is not a bug, I just added a test case to confirm.


The problem here is that in order to read data structures from environment variables, dynaconf needs one of 2 formats:

Toml by default

```
export PULP_DICT={key="value"}
```

Json if explicitly set

```
export PULP_DICT='@json {"key": "value"}'
```

Your example is not following any of those formats.

The test I made and worked is:

```
PULP_LOGGING='@json {"dynaconf_merge": true, "loggers": {"": {"handlers": ["console"], "level": "DEBUG"}}}'
```
