### ISSUE TITLE
Settings cannot load correctly in debug mode

### ISSUE THREAD

**Issue by Kyridiculous2** [rochacbruno/dynaconf#764]
When I use VScode to debug my python scripts, the settings cannot be load correctly, but it works fine when I directly run the scripts. How to solve this problem? 

When debug
![image](https://user-images.githubusercontent.com/26832000/176063765-307c4728-8e23-44ce-ac1d-cf8c9f374b41.png)

When  directly run it prints correctly
![image](https://user-images.githubusercontent.com/26832000/176063916-5d4c3c13-b7e3-49ce-8d9c-82797e29467a.png)

simple settings.yaml just like this

daily:
  recent_days: 365
  m_volume_day_thres: 30
  mvmp_width: 2
  c_volume_width: 3
  ###
  price_qs_maxday: 30
  min_price_days: 90

**Comment by rochacbruno** [comment]
This happens because VSCode working directory when debugging is probably different.

Please can you try:

```python
import os
ROOT_PATH = os.path.dirname(os.path.abspath(__file__))

settings = Dynaconf(
    ...
	root_path=ROOT_PATH
)

print(setting.daily)
```

**Comment by Kyridiculous2** [comment]
Solved! Thank you very much ! o(^▽^)o

**Comment by rochacbruno** [comment]
This will be properly fixed in 4.0 with #683

**Comment by bacalfa** [comment]
Hello, @rochacbruno. I'm having a similar problem, but I'm using PyCharm. And it's evern weirder because both Run and Debug modes work fine on one computer, but when I try to Debug on another computer, dynaconf seems to be getting an "older" version of the .toml files. I have NO explanation for this behavior. It's a version-controlled project, in which one branch has changes to the .toml file comapred to the "develop" branch. It seems that dynaconf is reading the data from the wrong branch (if that's even possible!) on one computer. The consequence is that I don't see the newly created variables that should be avaibale in the `settings` object. But everything works fine on another computer. Any suggestions?

**Comment by pedro-psb** [comment]
Hello @bacalfa . It is really hard to tell what is going on without being able to reproduce it, but I really don't think dynaconf can load from the wrong branch.

I can suggest the following:
- Double check you central repo and see if the setting files have the right contents and are in the branch they are expected. Maybe some change was not pushed right and you ended up with two different versions of you app.
- Try re-creating the project from scratch (cloning) on both pcs and check how it goes.
- Help me reproduce it by: (a) Sharing your repo (b) creating a minimal reproducible example

---

### template for creating a reproducible example

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:

1. Having the following folder structure



<details>
<summary> Project structure </summary>

```bash

# /path/
# ...../folder/...
# please provide your folder structure here

```
</details>

2. Having the following config files:



<details>
<summary> Config files </summary>

**/path/.env**
```bash
Your .env content here
```

and

**/path/settings.toml**
```toml
[default]
```

</details>

3. Having the following app code:

<details>
<summary> Code </summary>

**/path/src/app.py**
```python
from dynaconf import settings
...
```

</details>

4. Executing under the following environment

<details>
<summary> Execution </summary>

```bash
# other commands and details?
# virtualenv activation?

$ python /path/src/app.py
```

</details>

**Expected behavior**
A clear and concise description of what you expected to happen.

**Environment (please complete the following information):**
 - OS: [e.g. Linux/Fedora29, Windows/x.x.x, Linux/Ubuntu16.x]
 - Dynaconf Version [e.g. 2.0.0/source]
 - Frameworks in use (Flask, Django? versions..)

**Additional context**
Add any other context about the problem here.
